/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Dimuthu
 */
public class ProductAmount extends javax.swing.JFrame {

    /**
     * Creates new form ProductAmount
     */
    private JTextArea transDialog;
    private JTextField txt;
    private List<Cart> transactionItem = new ArrayList<>(); //this list will store all items to be used in this sale
    private String  name, id;
    private int amount_item;
    private float buy_price, sell_price;
    public ProductAmount() {
        initComponents();
    }
    
    public ProductAmount(List<Cart> transactionItem,JTextArea j, JTextField txt, String id, String name, float buy_price, float sell_price) {
        initComponents();
        this.transactionItem = transactionItem;
        this.txt = txt;
        this.transDialog = j;
        this.id = id;
        this.name = name;
        this.buy_price = buy_price;
        this.sell_price = sell_price;
        item.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        item = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        item.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        item.setText("Amount");

        amount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amount, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(item, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(amount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyPressed
        // TODO add your handling code here:
        int a = evt.getKeyCode();
        if(a==10){
            this.setVisible(false);
            amount_item = Integer.valueOf(amount.getText());
            Cart cart_item = new Cart(id, name, amount_item, buy_price, sell_price);
            transactionItem.add(cart_item);
            updateTextArea();
        }
    }//GEN-LAST:event_amountKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductAmount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductAmount().setVisible(true);
                
            }
        });
    }
    
    private void updateTextArea()
	{
	transDialog.setText(null);
        txt.setText(null);
        float total = 0;
        for (Cart temp: transactionItem)
        {
            //String itemString = temp.getItemID() + "\t" + temp.getItemName() + " \t" + "x" + temp.getAmount() + "\t$" + String.format("%.2f", temp.getAmount()*temp.getPrice()) + "\n";
            String itemString = temp.name+"\t"+temp.amount+"\t"+String.format("%.2f", temp.amount*temp.sell_price)+"\n";
            transDialog.append(itemString);
            total = total+temp.amount*temp.sell_price;
        }
        txt.setText(Float.toString(total));
        //if (operation.equals("Return") && (choice == 0))
        //	transDialog.append("\nTotal Price When Items Were Rented: $" + String.format("%.2f", transaction.getTotal()) + "\n" );
        //else
        //	transDialog.append("\nTotal: $" + String.format("%.2f", transaction.getTotal()) + "\n" );
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel item;
    // End of variables declaration//GEN-END:variables
}
